---
- name: install apache (red hat)
  yum:
    name: httpd
    state: latest
  when:
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version == "7"

- name: install apache (ubuntu )
  apt:
    name: httpd
    state: latest
  when:
    - ansible_distribution == "Ubuntu"

- name: start apache
  service:
    name: httpd
    state: started
    enabled: yes

- name: enable http port {{ http_port }} 
  firewalld:
    port: "{{ http_port }}/tcp"
    state: enabled
    permanent: true
  notify: restart firewall

- name: add the webserver admin user
  user:
    name: "{{ webadmin_name }}"
    home: /home/{{ webadmin_name }}
    #create_home: true
    password: "{{ webadmin_password }}"
    group: "{{ webadmin_group }}"
    shell: /bin/bash

- name: update apache config file
  template:
    src: templates/httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
  notify: restart apache

- name: update html file
  template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html
...
