---
- name: install or update common packages (red hat)
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - ntp
    - php
    - python
  when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "7")

- name: install or update common packages (ubuntu)
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - ntp
    - php
    - python
  when: (ansible_distribution == "Ubuntu")

- name: start common services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - ntpd

- name: update ntp config file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify: restart ntp
...
