---
- name: Remove apache2 webserver
  hosts: servers
  
  tasks:
  - name: stop apache
    ignore_errors: true
    service:
      name: httpd
      state: stopped
      enabled: no
  - name: disable http port (80)
    firewalld:
      port: 80/tcp
      state: disabled
      permanent: true 
    notify: restart firewall
  - name: remove apache
    yum:
      name: httpd
      state: absent

  handlers:
  - name: restart firewall
    service:
      name: firewalld
      state: restarted
...
