---
- name: simple playbook to remove webserver
  hosts: webservers
  
  vars:
    - http_port: 80
    - webadmin_user: webmaster

  tasks:
  - name: stop apache
    ignore_errors: true
    service:
      name: httpd
      state: stopped
      enabled: no
  - name: disable http port {{ http_port }}
    firewalld:
      port: "{{ http_port }}/tcp"
      state: disabled
      permanent: true 
    notify: restart firewall
  - name: remove apache
    yum:
      name: httpd
      state: absent
  - name: remove webadmin user {{ webadmin_user }}
    user:
      name: "{{ webadmin_user }}"
      state: absent

  handlers:
  - name: restart firewall
    service:
      name: firewalld
      state: restarted
...
