---
- name: simple playbook with vars for webserver
  hosts: webservers

  vars:
    - http_port: 80
    - webadmin_name: webmaster
    - webadmin_password: redhat
    - webadmin_group: root

  tasks:
  - name: install apache (red hat)
    yum:
      name: httpd
      state: latest
    when:
      - ansible_distribution == "RedHat"
      - ansible_distribution_major_version == "7"
    tags:
      - http
  - name: install apache (ubuntu )
    apt:
      name: httpd
      state: latest
    when:
      - ansible_distribution == "Ubuntu"
    tags:
      - http

  - name: start apache
    service:
      name: httpd
      state: started
      enabled: yes
    tags:
      - http

  - name: enable http port {{ http_port }}
    firewalld:
      port: "{{ http_port }}/tcp"
      state: enabled
      permanent: true
    notify: restart firewall
    tags:
      - http
      - firewall

  - name: add the webserver admin user
    user:
      name: "{{ webadmin_name }}"
      home: /home/{{ webadmin_name }}
      #create_home: true
      password: "{{ webadmin_password }}"
      group: "{{ webadmin_group }}"
      shell: /bin/bash
    tags:
      - http
      - webadmin

  handlers:
  - name: restart firewall
    service:
      name: firewalld
      state: restarted
...
